[build]
  base = "/"
  publish = "build/client/"
  command = "npm start"

# ---------------
# Redirects
# ---------------

[[redirects]]
  from = "/favicon.ico"
  to = "/img/favicon/favicon.ico"

[[redirects]]
  from = "/*"
  to = "/404?search=:splat"

# ---------------
# Headers
# ---------------

[[headers]]
  for = "/*"

  [headers.values]
    Content-Security-Policy = "script-src 'self' https://api.newprojectstarterkit.com https://npsk-express-starter.herokuapp.com"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Robots-Tag = "noindex, nofollow"

[[headers]]
  for = "/404/*"

  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

[[headers]]
  for = "/offline/*"

  [headers.values]
    X-Robots-Tag = "noindex, nofollow"