[build]
  base = "/"
  publish = "build/client/"
  command = "npm start"

[[redirects]]
  from = "/favicon.ico"
  to = "/img/favicon/favicon.ico"

[[redirects]]
  from = "/*"
  to = "/404?search=:splat"