[build]
  base = "/"
  publish = "build/client/"
  command = "npm start"

# ---------------
# Redirects
# ---------------

[[redirects]]
  from = "/favicon.ico"
  to = "/img/favicon/favicon.ico"

[[redirects]]
  from = "/*"
  to = "/404?search=:splat"

# ---------------
# Headers
# ---------------

[[headers]]
  for = "/*"

  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://api.newprojectstarterkit.com https://npsk-express-starter.herokuapp.com https://polyfill.io; connect-src 'self' https://api.newprojectstarterkit.com https://npsk-express-starter.herokuapp.com; form-action 'self' https://api.newprojectstarterkit.com https://npsk-express-starter.herokuapp.com"
    Feature-Policy = "geolocation 'none'; midi 'none'; notifications 'none'; push 'none'; sync-xhr 'self' https://api.newprojectstarterkit.com https://npsk-express-starter.herokuapp.com; microphone 'none'; camera 'none'; magnetometer 'none'; gyroscope 'none'; speaker 'none'; vibrate 'none'; fullscreen 'none'; payment 'none'"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Server = ""
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload" # 1 year
    X-Content-Security-Policy = "default-src 'self'; script-src 'self' https://api.newprojectstarterkit.com https://npsk-express-starter.herokuapp.com https://polyfill.io; connect-src 'self' https://api.newprojectstarterkit.com https://npsk-express-starter.herokuapp.com; form-action 'self' https://api.newprojectstarterkit.com https://npsk-express-starter.herokuapp.com" # IE fallback
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-Robots-Tag = "noindex, nofollow"
    X-Xss-Protection = "1; mode=block"

[[headers]]
  for = "/404/*"

  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

[[headers]]
  for = "/offline/*"

  [headers.values]
    X-Robots-Tag = "noindex, nofollow"