[build]
  base = "/"
  publish = "build/client/"
  command = "npm start"

# ---------------
# Redirects
# ---------------

[[redirects]]
  from = "/favicon.ico"
  to = "/img/favicon/favicon.ico"

[[redirects]]
  from = "/*"
  to = "/404?search=:splat"

# ---------------
# Headers
# ---------------

[[headers]]
  for = "/*"

  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

[[headers]]
  for = "/404/*"

  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

[[headers]]
  for = "/offline/*"

  [headers.values]
    X-Robots-Tag = "noindex, nofollow"